# tests/test_sv_to_python/test_generator.py
import pytest
from pathlib import Path
from datetime import datetime

from sv_to_python.parser import SVParser
from sv_to_python.extractor import UVMOperationExtractor
from sv_to_python.generator import PythonGenerator
from sv_to_python.ir import TaskInfo, RegWrite

FIXTURE_DIR = Path(__file__).parent.parent / "fixtures"

def test_generate_simple_task():
    """测试生成简单task"""
    # 创建测试task
    task = TaskInfo(
        name="test_task",
        parameters=[("value", "int")],
        operations=[
            RegWrite(
                line_no=10,
                original_source="reg.REG.write(status, 0x0001)",
                reg_path=["REG"],
                value=0x0001,
                backdoor=False
            )
        ]
    )

    generator = PythonGenerator()
    code = generator.generate_task(task)

    assert "def test_task(value):" in code
    assert "reg_model.reg.write(0x" in code
    assert "Auto-generated" in code

def test_generate_from_sv():
    """测试从SV文件生成"""
    parser = SVParser(FIXTURE_DIR / "uvm_tasks.sv")
    tasks_dict = parser.get_tasks()

    extractor = UVMOperationExtractor()

    # 转换为TaskInfo列表
    tasks = []
    for task_name, task_def in tasks_dict.items():
        operations = extractor.extract(task_def, parser.source_text)
        task_info = TaskInfo(
            name=task_name,
            parameters=task_def.parameters,
            operations=operations
        )
        tasks.append(task_info)

    generator = PythonGenerator()
    code = generator.generate_module(
        tasks,
        module_name="uvm_tasks",
        source_file=str(FIXTURE_DIR / "uvm_tasks.sv")
    )

    assert "def init_dma(" in code
    assert "def basic_write(" in code
    assert "Auto-generated by SV to Python converter" in code
    assert "dma_ctrl" in code.lower()

def test_format_value():
    """测试值格式化"""
    generator = PythonGenerator()

    assert generator._format_value(0x0001) == "0x00000001"
    assert generator._format_value(255) == "0x000000ff"
    assert generator._format_value("param") == "param"
