"""
C Header Code Generator

从RegisterBlock生成C头文件。
"""

from typing import Dict, Any
from .base import CodeGenerator


class CHeaderGenerator(CodeGenerator):
    """
    C头文件生成器

    从寄存器块生成C头文件，用于嵌入式软件访问寄存器。

    Args:
        use_hex: 是否使用十六进制常量（默认True）
        include_guard_prefix: 头文件保护前缀

    Example:
        >>> from rgm.core import RegisterBlock
        >>> from rgm.generators import CHeaderGenerator
        >>> gen = CHeaderGenerator()
        >>> code = gen.generate(block)
        >>> with open("uart_regs.h", "w") as f:
        ...     f.write(code)
    """

    def __init__(self, use_hex: bool = True, include_guard_prefix: str = "RGM"):
        self.use_hex = use_hex
        self.include_guard_prefix = include_guard_prefix

    def generate(self, block, **kwargs) -> str:
        """
        生成C头文件代码

        Args:
            block: RegisterBlock实例
            **kwargs: 额外参数

        Returns:
            C头文件代码字符串
        """
        lines = []

        # 文件头注释
        name_upper = block.name.upper()
        lines.append("/**")
        lines.append(f" * {block.name} Register Definitions")
        lines.append(f" * Base Address: 0x{block.base_address:X}")
        lines.append(" * Auto-generated by EDA_UFMV RGM")
        lines.append(" */")
        lines.append("")

        # 头文件保护
        guard_name = f"{self.include_guard_prefix}_{name_upper}_H_"
        lines.append(f"#ifndef {guard_name}")
        lines.append(f"#define {guard_name}")
        lines.append("")
        lines.append("#include <stdint.h>")
        lines.append("")

        # 基地址定义
        lines.append(f"// Base Address")
        lines.append(f"#define {name_upper}_BASE_ADDR 0x{block.base_address:08X}UL")
        lines.append("")

        # 寄存器偏移定义
        lines.append(f"// Register Offsets")
        for reg in block.get_registers():
            abs_addr = block.base_address + reg.offset
            lines.append(
                f"#define {name_upper}_{reg.name.upper()}_OFFSET 0x{reg.offset:04X}U"
            )
            lines.append(
                f"#define {name_upper}_{reg.name.upper()}_ADDR 0x{abs_addr:08X}UL"
            )
        lines.append("")

        # 位掩码定义
        lines.append(f"// Field Bit Masks")
        for reg in block.get_registers():
            for field in reg.get_fields():
                mask = field.get_mask()
                lines.append(
                    f"#define {name_upper}_{reg.name.upper()}_{field.name.upper()}_MASK 0x{mask:08X}U"
                )
        lines.append("")

        # 字段位置定义
        lines.append(f"// Field Bit Positions")
        for reg in block.get_registers():
            for field in reg.get_fields():
                lines.append(
                    f"#define {name_upper}_{reg.name.upper()}_{field.name.upper()}_SHIFT {field.bit_offset}U"
                )
                lines.append(
                    f"#define {name_upper}_{reg.name.upper()}_{field.name.upper()}_WIDTH {field.bit_width}U"
                )
        lines.append("")

        # 寄存器类型定义
        lines.append(f"// Register Type Definitions")
        lines.append(f"typedef union {{")
        lines.append(f"    uint32_t word;")
        lines.append(f"    struct {{")
        for reg in block.get_registers():
            if reg.get_fields():
                lines.append(f"        // {reg.name}")
                for field in reg.get_fields():
                    lines.append(
                        f"        uint32_t {field.name} : {field.bit_width};"
                    )
            else:
                lines.append(f"        // {reg.name} (no fields)")
        lines.append(f"    }} bits;")
        lines.append(f"}} {block.name}_regs_t;")
        lines.append("")

        # 内联函数定义
        name_lower = block.name.lower()
        lines.append(f"// Inline Access Functions")
        lines.append(f"static inline uint32_t {name_lower}_read(uint32_t offset) {{")
        lines.append(f"    return *(volatile uint32_t *)({name_upper}_BASE_ADDR + offset);")
        lines.append(f"}}")
        lines.append("")

        lines.append(f"static inline void {name_lower}_write(uint32_t offset, uint32_t value) {{")
        lines.append(f"    *(volatile uint32_t *)({name_upper}_BASE_ADDR + offset) = value;")
        lines.append(f"}}")
        lines.append("")

        # 头文件保护结束
        lines.append(f"#endif // {guard_name}")

        return "\n".join(lines)

    def get_file_extension(self) -> str:
        """
        获取文件扩展名

        Returns:
            ".h"
        """
        return ".h"

    def __repr__(self) -> str:
        return f"CHeaderGenerator(hex={self.use_hex}, guard={self.include_guard_prefix})"
