"""
Python Model Code Generator

Generate Python model code from RegisterBlock.
"""

from typing import Dict, Any
from .base import CodeGenerator


class PythonGenerator(CodeGenerator):
    """
    Python model code generator.

    Args:
        include_docstrings: Include docstrings (default: True)
        include_type_hints: Include type hints (default: True)

    Example:
        >>> gen = PythonGenerator()
        >>> code = gen.generate(block)
    """

    def __init__(self, include_docstrings: bool = True, include_type_hints: bool = True):
        self.include_docstrings = include_docstrings
        self.include_type_hints = include_type_hints

    def generate(self, block, **kwargs) -> str:
        """
        Generate Python model code.

        Args:
            block: RegisterBlock instance
            **kwargs: Additional parameters

        Returns:
            Python code string
        """
        lines = []

        # File header
        lines.append('"""')
        lines.append("{} Register Model".format(block.name))
        lines.append("")
        lines.append("Base Address: 0x{:X}".format(block.base_address))
        lines.append("Auto-generated by EDA_UFVM RGM")
        lines.append('"""')
        lines.append("")

        # Imports
        lines.append("from rgm.core import RegisterBlock, Register, Field")
        lines.append("from rgm.core import AccessType")
        lines.append("")

        # Class definition
        lines.append("class {}Model:".format(block.name))
        if self.include_docstrings:
            lines.append('    """')
            lines.append("    {} register model".format(block.name))
            lines.append('    """')
        lines.append("")

        # Init method
        lines.append("    def __init__(self):")
        lines.append("        super({0}Model, self).__init__(" .format(block.name))
        lines.append('            name="{}",'.format(block.name))
        lines.append("            base_address=0x{:X}".format(block.base_address))
        lines.append("        )")
        lines.append("")

        # Create registers
        for reg in block.get_registers():
            lines.append("        # {} @ 0x{:X}".format(reg.name, reg.offset))
            lines.append("        self.{} = Register(".format(reg.name.lower()))
            lines.append('            name="{}",'.format(reg.name))
            lines.append("            offset=0x{:02X},".format(reg.offset))
            lines.append("            width={},".format(reg.width))
            lines.append("            reset_value=0x{:X}".format(reg.reset_value))
            lines.append("        )")
            lines.append("")

            # Add fields
            for field in reg.get_fields():
                lines.append("        self.{}.add_field(".format(reg.name.lower()))
                lines.append("            Field(")
                lines.append('                name="{}",'.format(field.name))
                lines.append("                bit_offset={},".format(field.bit_offset))
                lines.append("                bit_width={},".format(field.bit_width))
                lines.append("                access=AccessType.{},".format(field.access.value))
                lines.append("                reset_value=0x{:X}".format(field.reset_value))
                lines.append("            )")
                lines.append("        )")
                lines.append("")

            lines.append("        self.add_register(self.{})".format(reg.name.lower()))
            lines.append("")

        # Access methods
        lines.append("    # Access methods")
        for reg in block.get_registers():
            type_hint = "-> int:" if self.include_type_hints else ""
            lines.append("    def read_{}(self){}".format(reg.name.lower(), type_hint))
            if self.include_docstrings:
                lines.append('        """')
                lines.append('        """Read {} register"""'.format(reg.name))
                lines.append('        """')
            lines.append("        return self.{}.read()".format(reg.name.lower()))
            lines.append("")

            lines.append("    def write_{}(self, value: int) -> None:".format(reg.name.lower()))
            if self.include_docstrings:
                lines.append('        """')
                lines.append('        """Write {} register"""'.format(reg.name))
                lines.append('        """')
            lines.append("        self.{}.write(value)".format(reg.name.lower()))
            lines.append("")

        return "\n".join(lines)

    def get_file_extension(self) -> str:
        """
        Get file extension.

        Returns:
            ".py"
        """
        return ".py"

    def __repr__(self) -> str:
        return "PythonGenerator(doc={}, types={})".format(
            self.include_docstrings, self.include_type_hints
        )
