"""
Verilog RTL Code Generator

从RegisterBlock生成Verilog RTL代码。
"""

from typing import List, Dict, Any
from .base import CodeGenerator


class VerilogGenerator(CodeGenerator):
    """
    Verilog代码生成器

    从寄存器块生成Verilog RTL代码。

    Args:
        include_reset: 是否包含复位逻辑（默认True）
        use_always_block: 使用always块还是assign（默认True）

    Example:
        >>> from rgm.core import RegisterBlock, Register, Field, AccessType
        >>> from rgm.generators import VerilogGenerator
        >>> block = RegisterBlock("UART", 0x4000_0000)
        >>> # ... 添加寄存器 ...
        >>> gen = VerilogGenerator()
        >>> code = gen.generate(block)
        >>> with open("uart_regs.v", "w") as f:
        ...     f.write(code)
    """

    def __init__(self, include_reset: bool = True, use_always_block: bool = True):
        self.include_reset = include_reset
        self.use_always_block = use_always_block

    def generate(self, block, **kwargs) -> str:
        """
        生成Verilog RTL代码

        Args:
            block: RegisterBlock实例
            **kwargs: 额外参数

        Returns:
            Verilog代码字符串
        """
        lines = []

        # 文件头注释
        lines.append("// Auto-generated Verilog RTL")
        lines.append(f"// Register Block: {block.name}")
        lines.append(f"// Base Address: 0x{block.base_address:X}")
        lines.append(f"// Generated by EDA_UFVM RGM v0.3.0")
        lines.append("")

        # 参数定义
        lines.append(f"module {block.name}_regs #(")
        lines.append("    parameter DATA_WIDTH = 32")
        lines.append(") (")
        lines.append("    input wire clk,")
        lines.append("    input wire rst_n,")
        lines.append("    // Bus Interface")
        lines.append("    input wire [DATA_WIDTH-1:0] addr,")
        lines.append("    input wire [DATA_WIDTH-1:0] wdata,")
        lines.append("    input wire write,")
        lines.append("    output reg [DATA_WIDTH-1:0] rdata")
        lines.append(");")
        lines.append("")

        # 寄存器声明
        lines.append("    // Register declarations")
        for reg in block.get_registers():
            lines.append(f"    reg [{reg.width-1}:0] {reg.name}_reg;")
        lines.append("")

        # 写逻辑
        if self.include_reset:
            lines.append("    // Write and Reset logic")
            lines.append("    always @(posedge clk or negedge rst_n) begin")
            lines.append("        if (!rst_n) begin")

            # 复位逻辑
            for reg in block.get_registers():
                lines.append(f"            {reg.name}_reg <= {reg.reset_value}'d{reg.width};")

            lines.append("        end else begin")
            lines.append("            // Write logic")
            lines.append("            if (write) begin")
            lines.append("                case (addr)")

            # 写入case
            for reg in block.get_registers():
                lines.append(f"                    {reg.offset}: {reg.name}_reg <= wdata;")

            lines.append("                    default: ;")
            lines.append("                endcase")
            lines.append("            end")
            lines.append("        end")
            lines.append("    end")
        else:
            lines.append("    // Write logic")
            lines.append("    always @(posedge clk) begin")
            lines.append("        if (write) begin")
            lines.append("            case (addr)")

            for reg in block.get_registers():
                lines.append(f"                {reg.offset}: {reg.name}_reg <= wdata;")

            lines.append("                default: ;")
            lines.append("            endcase")
            lines.append("        end")
            lines.append("    end")

        lines.append("")

        # 读逻辑
        lines.append("    // Read logic")
        lines.append("    always @(*) begin")
        lines.append("        case (addr)")
        for reg in block.get_registers():
            lines.append(f"            {reg.offset}: rdata = {reg.name}_reg;")
        lines.append("            default: rdata = 32'h0;")
        lines.append("        endcase")
        lines.append("    end")
        lines.append("")

        # 模块结束
        lines.append("endmodule")
        lines.append("")

        # 添加寄存器地址映射注释
        lines.append(f"// Address Map for {block.name}")
        lines.append(f"// Base Address: 0x{block.base_address:X}")
        for reg in block.get_registers():
            abs_addr = block.base_address + reg.offset
            lines.append(f"// 0x{abs_addr:08X}: {reg.name}")

        return "\n".join(lines)

    def get_file_extension(self) -> str:
        """
        获取文件扩展名

        Returns:
            ".v"
        """
        return ".v"

    def __repr__(self) -> str:
        return f"VerilogGenerator(reset={self.include_reset}, always={self.use_always_block})"
